// Front End Animes

export const GET_TOP_ANIME = 'GET_ANIME';
export const GET_SEASON_ANIME = 'GET_SEASON_ANIME';
export const SEARCH_ANIME = 'SEARCH_ANIME';

// Auth

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

// Back End Anime

export const GET_ANIME_LIST = "GET_ANIME_LIST";
export const REMOVE_ANIME_FROM_LIST = "REMOVE_ANIME_FROM_LIST";
export const ADD_BACK_ANIME = "ADD_BACK_ANIME";
export const CLEAR_LIST = "CLEAR_LIST";
export const UPDATE_EPISODE = "UPDATE_EPISODE";

// Media 

export const GET_POSTS = "GET_POSTS";
export const CREATE_POST = "CREATE_POST";
export const FILTER_POSTS = "FILTER_POSTS";
export const VOTE_POST = "VOTE_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";

// Community

export const CREATE_COMMUNITY = "CREATE_COMMUNITY";
export const SEARCH_COMMUNITIES = "SEARCH_COMMUNITIES";
export const SEARCH_COMMUNITY = "SEARCH_COMMUNITY";
export const GET_ALL_COMMUNITIES = "GET_ALL_COMMUNITIES";
export const SUB_UNSUB_COMMUNITIES = "SUB_UNSUB_COMMUNITIES";
export const UPDATE_SUB_UNSUB_COMMUNITY = "UPDATE_SUB_UNSUB_COMMUNITY";
export const REMOVE_MEMBER_FROM_COMMUNITY = "REMOVE_MEMBER_FROM_COMMUNITY";
export const BLOCK_MEMBER_FROM_COMMUNITY = "BLOCK_MEMBER_FROM_COMMUNITY";
export const ADD_ADMIN_TO_COMMUNITY = "ADD_ADMIN_TO_COMMUNITY";
export const ADD_REMOVE_MOD = "ADD_REMOVE_MOD";

// Comments

export const GET_COMMENTS = "GET_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const REPLY_COMMENT = "REPLY_COMMENT";
export const VOTE_COMMENT = "VOTE_COMMENT";